// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function query(req) {
  var partial_arg = req.query;
  return (function (param) {
      return partial_arg[param];
    });
}

exports.query = query;
/* No side effect */
